# Generated by Django 5.2 on 2025-05-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_pessoa_user_pessoa_usuario_alter_pessoa_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='is_gerente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em andamento'), ('concluida', 'Concluída'), ('ajuda', 'Preciso de ajuda')], default='pendente', max_length=20),
        ),
    ]
